### ISSUE TITLE
Followup to #13 (a missed classification inconsistency)

### ISSUE THREAD

**Issue by Farmbuyer** [nrollr/EC2-timeline#15]
Along the lines of issue #13:  The r6id family that got added this month should be classified as Memory Optimized, not Compute Optimized.  (#13 got r3 and r5 already, but according to https://aws.amazon.com/ec2/instance-types/ all of the "R" category are tagged as Memory Optimized.)

**Comment by nrollr** [comment]
Thanks for pointing this out @Farmbuyer! 
It seems the wrong classification was used on the webpage, while the [json source](https://instancetyp.es/timeline.json) contains the correct classification for the R6id instances.
