### ISSUE TITLE
C4 and T2 Instances still showing as current

### ISSUE THREAD

**Issue by Beccles-Ben** [nrollr/EC2-timeline#18]
Hi

C4 and T2 Instances still showing as current - I believe they should have been replaced by C5 and T3 respectively?

**Comment by nrollr** [comment]
Hi Ben,

The C4 and T2 instances are indeed an older generation, yet are still available for deployment.

Perhaps the indication "Current" vs "Previous" generation should be changed to avoid confusion, as "Current" equals 'available', while "Previous" refers to older instances which are 'no longer available'.

**Comment by Beccles-Ben** [comment]
Hi

Thanks for getting back to me!

It seems I need to find a new list then as I'm using this list to provide me with a 'generation age' list which I'm using to determine savings recommendations for cost optimisation based on upgrading to the latest generation.

Regards

[Rackspace Technology]<https://rackspace.com/en-gb>
Ben Nicholson
[Facebook]<https://facebook.com/RackspaceUK>
[Twitter]<https://twitter.com/RackspaceUK>
[Linkedin]<https://www.linkedin.com/in/ben-nicholson/>
[Rackspace]<https://rackspace.com/en-gb>
Email: ***@***.******@***.***>
***@***.***<https://rackspace.com/learn-more>
Adaptability + Empathy + Ideation + Relator + Restorative
