### ISSUE TITLE
Missing r7iz

### ISSUE THREAD

**Issue by lart2150** [nrollr/EC2-timeline#20]
https://aws.amazon.com/about-aws/whats-new/2022/11/introducing-amazon-ec2-r7iz-instances/
https://aws.amazon.com/ec2/instance-types/r7iz/

**Comment by nrollr** [comment]
Hi @lart2150,

indeed EC2 R7iz instances were announced on Nov 28 -I believe during re:Invent- however these instances are initially available **in preview**. The timeline only documents new EC2 releases as soon as they hit **general availability**, hence the reason why they are not showing on the timeline (yet).

The same logic also applies to [Inf2 instances](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-announces-amazon-ec2-inf2-instances-preview/) and [C7gn instances](https://aws.amazon.com/about-aws/whats-new/2022/11/announcing-amazon-ec2-c7gn-instances-preview/)
