### ISSUE TITLE
C5 instance release date.

### ISSUE THREAD

**Issue by GenerallyPrettyQuiet** [nrollr/EC2-timeline#3]
This is my first comment ever on GitHub, so I apologize if the formatting or style is off. 

Your EC2 time-line (which is great) shows that the C5 instance was created in December 2016, but they weren't created until November of 2017.

Release in November 2017: https://www.businesswire.com/news/home/20171106006573/en/AWS-Announces-Availability-C5-Instances-Amazon-EC2
Blog Announcement: https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/
News on the 2017 launch announcement
https://cloudcomputing-news.net/news/2017/nov/09/aws-launches-c5-instances-ec2-alongside-new-cloud-optimised-hypervisor/

**Comment by nrollr** [comment]
Hi @GenerallyPrettyQuiet 
Thank you for reviewing the timeline data! Much appreciated 👍🏻
You are correct, the C5 instances were actually made available in 2017, not 2016

While reviewing the [data-sources](https://github.com/nrollr/EC2-timeline/tree/master/data) I noticed all the C5 instances were tagged Nov 2017, while the [announcement](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/) and corresponding [blog post](https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/) were actually refering to the correct date. Must have been a typo..

I updated all relevant files and will release v1.2.2 ! 🎉
Thanks again for your contribution 😉
