### ISSUE TITLE
Missing u-6tb1.* instance types (not metal)

### ISSUE THREAD

**Issue by silvexis** [nrollr/EC2-timeline#4]
see https://aws.amazon.com/about-aws/whats-new/2021/05/four-ec2-high-memory-instances-with-up-to-12tb-memory-available-with-on-demand-and-savings-plan-purchase-options/

**Comment by silvexis** [comment]
FYI, I'm happy to open a PR, but not sure that's desired? The files looked generated and I wasn't sure how you would want me to generate the UID

**Comment by nrollr** [comment]
Hi @silvexis,

thank you for reviewing the timeline data with scrutiny! 🤓 
I noticed you posted several issues, which is a good thing, I'll review them all and create a separate PR's linking to the different issues + make the necessary adjustments  👍🏻
