### ISSUE TITLE
Missing r5n.16xlarge and r5dn.16xlarge

### ISSUE THREAD

**Issue by silvexis** [nrollr/EC2-timeline#5]
See https://aws.amazon.com/blogs/aws/new-m5n-and-r5n-instances-with-up-to-100-gbps-networking/

**Comment by nrollr** [comment]
Hi @silvexis 

These are indeed missing... additionally the **m5n.16xlarge** and **m5dn.16xlarge** instances -also mentioned in the blog post- seem to be missing from the datasets ([.json](https://github.com/nrollr/EC2-timeline/blob/master/public/timeline.json), [.sql](https://github.com/nrollr/EC2-timeline/blob/master/public/data/timeline.sql) and [.csv](https://github.com/nrollr/EC2-timeline/blob/master/public/data/timeline.csv)) as well. 

However, they were mentioned on the [landing page](https://instancetyp.es) correctly.
